### ISSUE TITLE
Your benchmarks are ignoring warmup

### ISSUE THREAD

**Issue by wirthi** [Ivan-Kouznetsov/graalvm-perf#4]
Hi @Ivan-Kouznetsov 

thanks for those benchmarks. As I describe in more detail in https://github.com/graalvm/graaljs/issues/74#issuecomment-730429272 they do ignore warmup, though. 1000 iterations that take a 120ms (or even 2 seconds) cannot be considered proper warmup. Admittedly, GraalVM currently is not a good match for any short-running console/filter like tool; its target are long-running server applications. 

If you fix the warmup problem and measure only peak performance (again, see https://github.com/graalvm/graaljs/issues/74#issuecomment-730429272 for one example) you will see a much different picture than you present here:

- On the JSON benchmarks, GraalVM either outperforms or matches V8. 
- On the RegExp benchmark, GraalVM is (only) ~3x behind (something we should fix).

Best,
Christian

**Comment by Ivan-Kouznetsov** [comment]
Thanks, merged
